language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: OOL4HywJyhYKZksc91fw/LcVo7F5B2eELQGEl6fnA34ZpH3HE822ZgjcRzWto2vZPYvgq5TZ7vSe2+ci9ghFz5cqOdEJ5l/34C61FBsEwsYdngnU7LQGEoILZdC6AbbYbzsBzS75MDhARNxb/1945tUzgeaRmwrRDfGjvNZdfjDnvaCp0DVJrJMe2GM04UP3Qw/xnJPH/Y/cZP9m8K2zLEuNKdBLNsP8VgTT5T8q910XrTlXLjKo/xyqVY0GXJEk4BIicpbUng03coFUhUNG03/nmeiRjL9hnMt+alpwmBPRNH2nKglTuFZivxyKf7OyQNigCM2Hii5xk9llHk/yi5taKxaj3oXE2QAWifrSruoFl3uHZ5WCwfpUqR9wmfvZdOr25TIcqBg7Nct3u9doIvzXWHRX3JmsRIpB8tR2W6u/IyfGOcderz4g7viS4OQHsfFzIsLnk23JwxoHCVN0fgqs5Cpgw0fnNL2Xp0yMJEkV/L95IBoLg8wuJ4rr8ZvnqsFw/5Zwd3b33O1LaMhbI/HJf0rwfjxDk16oCQLDxA0/axSbWOhr2ZdbAlGxQTpJqjDp8bAAnZfwYSrJ2QhXic8BGhesYWAmTFxn5hznV88uP1TIeiLMRLC4AvVXxXHzRMhCJ0Qs2Abh0hyWrFxw3S//AJBISi7XqCsertkbpm8=
  app: damp-garden-35226
  on:
    repo: sethjensenbrown/pitted
